prSections:
- title: My PRs
  filters: is:open author:@me
- title: Review Requested
  filters: is:open review-requested:@me
- title: Connect PRs
  filters: is:open -author:@me repo:bufbuild/connect-go repo:bufbuild/connect-grpchealth-go repo:bufbuild/connect-grpcreflect-go repo:bufbuild/connect-crosstest
issuesSections:
- title: My Issues
  filters: is:open author:@me
- title: Assigned
  filters: is:open assignee:@me
- title: Subscribed
  filters: is:open -author:@me repo:bufbuild/connect-go repo:bufbuild/connect-grpchealth-go repo:bufbuild/connect-grpcreflect-go repo:bufbuild/connect-crosstest
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: prs
